### ISSUE TITLE
Daedalus addresses not correct?

### ISSUE THREAD

**Issue by 0xtrossets** [vacuumlabs/cardano-crypto.js#41]
I'm following the examples to generate a Daedalus address, but it seems to produce a different address compared to the same mnemonic and derivation as cardano-wallet.
Any ideas as to why there's a difference in address?

**Comment by refi93** [comment]
Hi @0xtrossets could you please provide a specific example of where this lib differs from cardano-wallet?

**Comment by Fell-x27** [comment]
I can.

Mnemonic: `island virus author music close winner opera surge noodle mandate network filter`
Path: `[2147483648, 2462157060]`
Testnet magic: `1`
cardano-crypto addr: `KjgoiXJS2cosJco6i5438GrauQmBfY7zmu1weoEGmDzruUdLDxWyKwQ7RAkR8CjcXCMqZB1FJu2da3phAce2DvtKuSvuu1dxHa46E45EXFeJ`
cardano-wallet addr: `KjgoiXJS2coLwHDxzPoYv96jtVzLG1uFfESzUhS1KjNoN7BamnvjkDNs33PQKkGULLqyPF5A2QGpModCjwG8DUEXjDM3LyxcqHaE5EBD5nAS`

We can send funds to `KjgoiXJS2coLwHDxzPoYv96jtVzLG1uFfESzUhS1KjNoN7BamnvjkDNs33PQKkGULLqyPF5A2QGpModCjwG8DUEXjDM3LyxcqHaE5EBD5nAS`, but can't spend from it.

**Comment by MichalPetro** [comment]
@PeterBenc can you try to reproduce pls?

**Comment by refi93** [comment]
@Fell-x27 I tried plugging the mnemonic, derivation path and derivation scheme into cardano-crypto.js and got a different address, of course I may have missed something. Could you please attach the code snippet to reproduce the `...BD5nAS` address?

```javascript
  var lib = require("cardano-crypto.js")

const mnemonic =
    "island virus author music close winner opera surge noodle mandate network filter";
  const path = [2147483648, 2462157060];
  const derivationScheme = 1
  const magic = 1

  const rootKeypair = await lib.mnemonicToRootKeypair(mnemonic, derivationScheme);

  const hdNodeL1 = lib.derivePrivate(rootKeypair, path[0], derivationScheme);
  const hdNodeL2 = lib.derivePrivate(hdNodeL1, path[1], derivationScheme);
  const xpubL2 = hdNodeL2.slice(64, 128);
  const hdPassphrase = await lib.xpubToHdPassphrase(xpubL2);

  const addressRaw = lib.packBootstrapAddress(path, xpubL2, hdPassphrase, derivationScheme, magic);
  const addressBase58 = lib.base58.encode(addressRaw);

  console.log(addressBase58); // KjgoiXJS2coYFTNgXMU3DSq3eZy4ibFxf8xM1JYXsYyqaEMwHUEWxYCrAjLbaSf1VKYSkcHD7ZCLcfhmhX5mYmWxc8ZRkp2NReq3D9LF4Aaz
```
The snippet above can be ran e.g. with runkit: https://npm.runkit.com/cardano-crypto.js

**Comment by Fell-x27** [comment]
>KjgoiXJS2coYFTNgXMU3DSq3eZy4ibFxf8xM1JYXsYyqaEMwHUEWxYCrAjLbaSf1VKYSkcHD7ZCLcfhmhX5mYmWxc8ZRkp2NReq3D9LF4Aaz

I'm afraid this address is more wrong than my previous one. You can't even receive any funds with it. It has to be `KjgoiXJS2cosJco6i5438GrauQmBfY7zmu1weoEGmDzruUdLDxWyKwQ7RAkR8CjcXCMqZB1FJu2da3phAce2DvtKuSvuu1dxHa46E45EXFeJ`.

If you want to get `D5nAS`, you have to use root-xPub for hdPass **and** for packing. We need exactly root-pub if we want to produce a correct authentication part of the address to be able to confirm it as a part of our address set.

Yes, it was my mistake to use the root xpub as an addresses' one, so I got a broken "address root" and can't spend funds from it. But... if you'll use the root-pub for hdPass and addr-level-pub for address packing, you will get the wrong address too. It will be able to receive funds, but still not able to spend it.

It's something with the library and its address-root building algorithm I think.

**Comment by Fell-x27** [comment]
I've found a problem. Wait for the PR :)

**Comment by Fell-x27** [comment]
@refi93 , I fixed it: https://github.com/vacuumlabs/cardano-crypto.js/pull/42

**Comment by Fell-x27** [comment]
@refi93 , here is a fix https://github.com/vacuumlabs/cardano-crypto.js/pull/43

Works fine for both mainnet and testnet, v1 and v2 types. All addrs are the same as cardano wallet derives.

**Comment by refi93** [comment]
the PR has been merged and fixed version of cardano-crypto.js published on npm (6.1.2), thanks @Fell-x27 !

note: the issue concerns just testnet Byron addresses, mainnet addresses weren't affected as they are packed differently, therefore actual (mainnet) users weren't impacted by this bug

**Comment by refi93** [comment]
> @Fell-x27 thanks for adding details - I tried plugging the mnemonic, derivation path and derivation scheme into cardano-crypto.js and got a different address, of course I may have missed something. Could you please attach the code snippet to reproduce the `...BD5nAS` address?
> 
> ```js
>   var lib = require("cardano-crypto.js") // v6.1.1
> 
>   const mnemonic =
>     "island virus author music close winner opera surge noodle mandate network filter";
>   const path = [2147483648, 2462157060];
>   const derivationScheme = 1
>   const magic = 1
> 
>   const rootKeypair = await lib.mnemonicToRootKeypair(mnemonic, derivationScheme);
> 
>   const hdNodeL1 = lib.derivePrivate(rootKeypair, path[0], derivationScheme);
>   const hdNodeL2 = lib.derivePrivate(hdNodeL1, path[1], derivationScheme);
>   const xpubL2 = hdNodeL2.slice(64, 128);
>   const hdPassphrase = await lib.xpubToHdPassphrase(xpubL2);
> 
>   const addressRaw = lib.packBootstrapAddress(path, xpubL2, hdPassphrase, derivationScheme, magic);
>   const addressBase58 = lib.base58.encode(addressRaw);
> 
>   console.log(addressBase58); // KjgoiXJS2coYFTNgXMU3DSq3eZy4ibFxf8xM1JYXsYyqaEMwHUEWxYCrAjLbaSf1VKYSkcHD7ZCLcfhmhX5mYmWxc8ZRkp2NReq3D9LF4Aaz
> ```
> 
> The snippet above can be ran e.g. with runkit: https://npm.runkit.com/cardano-crypto.js

note for anybody checking this thread:

this is the correct way to obtain the hdPassphrase in the snippet above:
```javascript
  const xpubForHdPassphrase = rootKeypair.slice(64, 128);
  const hdPassphrase = await lib.xpubToHdPassphrase(xpubForHdPassphrase);
```

**Comment by 0xtrossets** [comment]
@Fell-x27 Can you provide the full code snippet you used to make it work? I'm trying with the parameters you provided, but still not getting the correct address (`KjgoiXJS2cosJco6i5438GrauQmBfY7zmu1weoEGmDzruUdLDxWyKwQ7RAkR8CjcXCMqZB1FJu2da3phAce2DvtKuSvuu1dxHa46E45EXFeJ`)

v6.1.1 yields what you got before: `KjgoiXJS2coLwHDxzPoYv96jtVzLG1uFfESzUhS1KjNoN7BamnvjkDNs33PQKkGULLqyPF5A2QGpModCjwG8DUEXjDM3LyxcqHaE5EBD5nAS`
v6.1.2 yields: `KjgoiXJS2cokzXxLdgftJ3bEZW48zJdNTsL817dWKsg8xwU3fGmXn64jvvchq7m4QTkMHAjC8HZXzdKQE2SEnWu5jn6cwfYknFQbFZFdsR7H`

---

nevermind, I re-read your comment about deriving the xprv for address packing. Works now!
